stereo_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  neck_effort_controller:
    type: effort_controllers/JointEffortController
    joint: neck_to_base
    pid: {p: 100.0, i: 0.01, d: 10.0}