stereo_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers (This allows to control the neck as if it was connected to a servo)
  neck_position_controller:
    type: position_controllers/JointPositionController
    joint: neck_to_base
    pid: {p: 100.0, i: 0.01, d: 10.0}